const motivationalQuotes = [
  "Don't watch the clock; do what it does. Keep going.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "Don't wait for opportunity. Create it.",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The way to get started is to quit talking and begin doing.",
  "Your time is limited, don't waste it living someone else's life.",
  "The best way to predict the future is to invent it.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Don't be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "You are never too old to set another goal or to dream a new dream.",
  "Act as if what you do makes a difference. It does.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "It always seems impossible until it’s done.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "The only place where success comes before work is in the dictionary.",
  "You don’t have to be great to start, but you have to start to be great.",
  "The future depends on what you do today.",
  "Start where you are. Use what you have. Do what you can.",
  "You are never too small to make a difference.",
  "We must not allow other people’s limited perceptions to define us.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Do not wait to strike till the iron is hot; but make it hot by striking.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "The best revenge is massive success.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "Don’t watch the clock; do what it does. Keep going.",
  "If you can dream it, you can do it.",
  "You are braver than you believe, stronger than you seem, and smarter than you think."
];

export default motivationalQuotes;
